const envs = {
  ALGOR_ORCH_BASE_SERVICE_ENDPOINT: window.ALGOR_ORCH_BASE_SERVICE_ENDPOINT,
  COMMON_LOGIN_DOMAIN: window.COMMON_LOGIN_DOMAIN,
  EASY_DOCK_BASE_SERVICE_ENDPOINT: window.EASY_DOCK_BASE_SERVICE_ENDPOINT,
  ALGOR_ORCH_FRONTEND_ENTRY: window.ALGOR_ORCH_FRONTEND_ENTRY,
  EASY_FLOW_FRONTEND_ENTRY: window.EASY_FLOW_FRONTEND_ENTRY,
  EASY_CHART_FRONTEND_ENTRY: window.EASY_CHART_FRONTEND_ENTRY,
};

export default envs;
