const componentSchema = {
  Input: {
    baseInfo: {
      name: '单行文本',
      icon: 'danhangwenben',
      category: '基础控件',
      version: '1.0',
      type: 'Input',
    },
    config: [
      {
        key: 'fieldName',
        defaultValue: '',
        label: '数据库字段名',
        placeholder: '字母开头,数字或下划线组成',
        type: 'Input',
        direction: 'vertical',
        required: true,
        requiredMessage: '请输入数据库字段名',
        rules: [
          { pattern: '^[a-zA-Z][a-zA-Z0-9_]{0,29}$', message: '请输入字母开头，包含字母、数字、下划线的1-30位字符' },
        ],
        isProps: false,
      },
      {
        key: 'label',
        defaultValue: '单行文本',
        label: '控件名称',
        placeholder: '请输入',
        type: 'Input',
        direction: 'vertical',
        required: true,
        requiredMessage: '请输入控件名称',
        isProps: false,
      },
      {
        key: 'desc',
        defaultValue: '',
        label: '提示语',
        placeholder: '请输入',
        type: 'Input',
        direction: 'vertical',
        required: false,
        isProps: false,
      },
      {
        key: 'defaultValue',
        defaultValue: '',
        label: '默认值',
        placeholder: '请输入',
        type: 'Input',
        direction: 'vertical',
        required: false,
        isProps: true,
      },
      {
        key: 'unique',
        defaultValue: false,
        label: '不允许重复值',
        type: 'Switch',
        direction: 'vertical',
        required: false,
        isProps: false,
      },
      {
        key: 'colSpace',
        defaultValue: '4',
        label: '控件宽度',
        type: 'ColSpace',
        direction: 'vertical',
        required: false,
        isProps: false,
      },
    ],
  },
  Textarea: {
    baseInfo: {
      name: '多行文本',
      icon: 'duohangcaidan',
      category: '基础控件',
      version: '1.0',
      type: 'Textarea',
    },
    config: [
      {
        key: 'fieldName',
        defaultValue: '',
        label: '数据库字段名',
        placeholder: '字母开头,数字或下划线组成',
        type: 'Input',
        direction: 'vertical',
        required: true,
        requiredMessage: '请输入数据库字段名',
        rules: [
          { pattern: '^[a-zA-Z][a-zA-Z0-9_]{0,29}$', message: '请输入字母开头，包含字母、数字、下划线的1-30位字符' },
        ],
        isProps: false,
      },
      {
        key: 'label',
        defaultValue: '多行文本',
        label: '控件名称',
        placeholder: '请输入',
        type: 'Input',
        direction: 'vertical',
        required: true,
        requiredMessage: '请输入控件名称',
        isProps: false,
      },
      {
        key: 'desc',
        defaultValue: '',
        label: '提示语',
        placeholder: '请输入',
        type: 'Input',
        direction: 'vertical',
        required: false,
        isProps: false,
      },
      {
        key: 'defaultValue',
        defaultValue: '',
        label: '默认值',
        placeholder: '请输入',
        type: 'Textarea',
        direction: 'vertical',
        required: false,
        isProps: false,
      },
      {
        key: 'colSpace',
        defaultValue: '4',
        label: '控件宽度',
        type: 'ColSpace',
        direction: 'vertical',
        required: false,
        isProps: false,
      },
    ],
  },
  Select: {
    baseInfo: {
      name: '下拉框',
      icon: 'xialakuang',
      category: '基础控件',
      version: '1.0',
      type: 'Select',
    },
    config: [
      {
        key: 'fieldName',
        defaultValue: '',
        label: '数据库字段名',
        placeholder: '字母开头,数字或下划线组成',
        type: 'Input',
        direction: 'vertical',
        required: true,
        requiredMessage: '请输入数据库字段名',
        rules: [
          { pattern: '^[a-zA-Z][a-zA-Z0-9_]{0,29}$', message: '请输入字母开头，包含字母、数字、下划线的1-30位字符' },
        ],
        isProps: false,
      },
      {
        key: 'label',
        defaultValue: '下拉框',
        label: '控件名称',
        placeholder: '请输入',
        type: 'Input',
        direction: 'vertical',
        required: true,
        requiredMessage: '请输入控件名称',
        isProps: false,
      },
      {
        key: 'desc',
        defaultValue: '',
        label: '提示语',
        placeholder: '请输入',
        type: 'Input',
        direction: 'vertical',
        required: false,
        isProps: false,
      },
      // {
      //   key: 'defaultValue',
      //   defaultValue: '',
      //   label: '默认值',
      //   placeholder: '请选择',
      //   type: 'SelectDefaultOption',
      //   direction: 'vertical',
      // },
      {
        key: 'multiple',
        defaultValue: false,
        label: '是否多选',
        type: 'Switch',
        direction: 'horizontal',
        required: false,
        isProps: true,
      },
      {
        key: 'showSearch',
        defaultValue: false,
        label: '是否可搜索',
        type: 'Switch',
        direction: 'horizontal',
        required: false,
        isProps: true,
      },
      {
        key: 'dataSource',
        defaultValue: {
          type: 'custom',
          data: [
            { key: '选项一', value: '选项一' },
            { key: '选项二', value: '选项二' },
            { key: '选项三', value: '选项三' },
          ],
        },
        label: '选项内容',
        type: 'SelectOptionList',
        direction: 'vertical',
        required: true,
        isProps: false,
      },
      {
        key: 'colSpace',
        defaultValue: '4',
        label: '控件宽度',
        type: 'ColSpace',
        direction: 'vertical',
        required: false,
        isProps: false,
      },
    ],
  },
  Radio: {
    baseInfo: {
      name: '单选',
      icon: 'danxuankuang',
      category: '基础控件',
      version: '1.0',
      type: 'Radio',
    },
    config: [
      {
        key: 'fieldName',
        defaultValue: '',
        label: '数据库字段名',
        placeholder: '字母开头,数字或下划线组成',
        type: 'Input',
        direction: 'vertical',
        required: true,
        requiredMessage: '请输入数据库字段名',
        rules: [
          { pattern: '^[a-zA-Z][a-zA-Z0-9_]{0,29}$', message: '请输入字母开头，包含字母、数字、下划线的1-30位字符' },
        ],
        isProps: false,
      },
      {
        key: 'label',
        defaultValue: '单选框',
        label: '控件名称',
        placeholder: '请输入',
        type: 'Input',
        direction: 'vertical',
        required: true,
        requiredMessage: '请输入控件名称',
        isProps: false,
      },
      {
        key: 'desc',
        defaultValue: '',
        label: '提示语',
        placeholder: '请输入',
        type: 'Input',
        direction: 'vertical',
        required: false,
        isProps: false,
      },
      {
        key: 'dataSource',
        defaultValue: {
          type: 'custom',
          data: [
            { key: '选项一', value: '选项一' },
            { key: '选项二', value: '选项二' },
            { key: '选项三', value: '选项三' },
          ],
        },
        label: '选项内容',
        type: 'SelectOptionList',
        direction: 'vertical',
        required: true,
        isProps: false,
      },
      {
        key: 'colSpace',
        defaultValue: '4',
        label: '控件宽度',
        type: 'ColSpace',
        direction: 'vertical',
        required: false,
        isProps: false,
      },
    ],
  },
  Checkbox: {
    baseInfo: {
      name: '复选',
      icon: 'duoxuankuang',
      category: '基础控件',
      version: '1.0',
      type: 'Checkbox',
    },
    config: [
      {
        key: 'fieldName',
        defaultValue: '',
        label: '数据库字段名',
        placeholder: '字母开头,数字或下划线组成',
        type: 'Input',
        direction: 'vertical',
        required: true,
        requiredMessage: '请输入数据库字段名',
        rules: [
          { pattern: '^[a-zA-Z][a-zA-Z0-9_]{0,29}$', message: '请输入字母开头，包含字母、数字、下划线的1-30位字符' },
        ],
        isProps: false,
      },
      {
        key: 'label',
        defaultValue: '复选框',
        label: '控件名称',
        placeholder: '请输入',
        type: 'Input',
        direction: 'vertical',
        required: true,
        requiredMessage: '请输入控件名称',
        isProps: false,
      },
      {
        key: 'desc',
        defaultValue: '',
        label: '提示语',
        placeholder: '请输入',
        type: 'Input',
        direction: 'vertical',
        required: false,
        isProps: false,
      },
      {
        key: 'dataSource',
        defaultValue: {
          type: 'custom',
          data: [
            { key: '选项一', value: '选项一' },
            { key: '选项二', value: '选项二' },
            { key: '选项三', value: '选项三' },
          ],
        },
        label: '选项内容',
        type: 'SelectOptionList',
        direction: 'vertical',
        required: false,
        isProps: false,
      },
      {
        key: 'colSpace',
        defaultValue: '4',
        label: '控件宽度',
        type: 'ColSpace',
        direction: 'vertical',
        required: false,
        isProps: false,
      },
    ],
  },
  Date: {
    baseInfo: {
      name: '日期',
      icon: 'riqi',
      category: '基础控件',
      version: '1.0',
      type: 'Date',
    },
    config: [
      {
        key: 'fieldName',
        defaultValue: '',
        label: '数据库字段名',
        placeholder: '字母开头,数字或下划线组成',
        type: 'Input',
        direction: 'vertical',
        required: true,
        requiredMessage: '请输入数据库字段名',
        rules: [
          { pattern: '^[a-zA-Z][a-zA-Z0-9_]{0,29}$', message: '请输入字母开头，包含字母、数字、下划线的1-30位字符' },
        ],
        isProps: false,
      },
      {
        key: 'label',
        defaultValue: '日期',
        label: '控件名称',
        placeholder: '请输入',
        type: 'Input',
        direction: 'vertical',
        required: true,
        requiredMessage: '请输入控件名称',
        isProps: false,
      },
      {
        key: 'desc',
        defaultValue: '',
        label: '提示语',
        placeholder: '请输入',
        type: 'Input',
        direction: 'vertical',
        required: false,
        isProps: false,
      },
      {
        key: 'format',
        defaultValue: 'YYYY-MM-DD',
        label: '显示格式',
        placeholder: '请选择',
        type: 'Select',
        direction: 'vertical',
        range: [
          {
            key: 'YYYY-MM-DD',
            value: '年-月-日',
          },
          {
            key: 'YYYY-MM-DD HH:mm:ss',
            value: '年-月-日 时:分:秒',
          },
        ],
        required: false,
        isProps: true,
      },
      {
        key: 'notSelectPassed',
        defaultValue: false,
        label: '禁止选择已过去的时间',
        type: 'Switch',
        direction: 'horizontal',
        required: false,
        isProps: false,
      },
      {
        key: 'defaultValue',
        defaultValue: '',
        label: '默认值',
        placeholder: '选择日期',
        type: 'DefaultDate',
        direction: 'vertical',
        required: false,
        isProps: true,
      },
      {
        key: 'colSpace',
        defaultValue: '4',
        label: '控件宽度',
        type: 'ColSpace',
        direction: 'vertical',
        required: false,
        isProps: false,
      },
    ],
  },
  InputNumber: {
    baseInfo: {
      name: '数字',
      icon: 'shuzi123',
      category: '基础控件',
      version: '1.0',
      type: 'InputNumber',
    },
    config: [
      {
        key: 'fieldName',
        defaultValue: '',
        label: '数据库字段名',
        placeholder: '字母开头,数字或下划线组成',
        type: 'Input',
        direction: 'vertical',
        required: true,
        requiredMessage: '请输入数据库字段名',
        rules: [
          { pattern: '^[a-zA-Z][a-zA-Z0-9_]{0,29}$', message: '请输入字母开头，包含字母、数字、下划线的1-30位字符' },
        ],
        isProps: false,
      },
      {
        key: 'label',
        defaultValue: '数字',
        label: '控件名称',
        placeholder: '请输入',
        type: 'Input',
        direction: 'vertical',
        required: true,
        requiredMessage: '请输入控件名称',
        isProps: false,
      },
      {
        key: 'desc',
        defaultValue: '',
        label: '提示语',
        placeholder: '请输入',
        type: 'Input',
        direction: 'vertical',
        required: false,
        isProps: false,
      },
      {
        key: 'defaultValue',
        defaultValue: '',
        label: '默认值',
        placeholder: '请输入',
        type: 'InputNumber',
        direction: 'vertical',
        required: false,
        isProps: false,
      },
      {
        key: 'colSpace',
        defaultValue: '4',
        label: '控件宽度',
        type: 'ColSpace',
        direction: 'vertical',
        required: false,
        isProps: false,
      },
    ],
  },
  DescText: {
    baseInfo: {
      name: '描述文字',
      icon: 'xiangqing',
      category: '基础控件',
      version: '1.0',
      type: 'DescText',
    },
    config: [
      {
        key: 'label',
        defaultValue: '描述文字',
        label: '控件名称',
        placeholder: '请输入',
        type: 'Input',
        direction: 'vertical',
        required: true,
        requiredMessage: '请输入控件名称',
        isProps: false,
      },
      {
        key: 'value',
        defaultValue: '',
        label: '内容',
        type: 'Editor',
        direction: 'vertical',
        required: true,
        isProps: false,
      },
      {
        key: 'colSpace',
        defaultValue: '4',
        label: '控件宽度',
        type: 'ColSpace',
        direction: 'vertical',
        required: false,
        isProps: false,
      },
    ],
  },
};

export default componentSchema;
