//import {Schema} from '@type'
const model = {
  subApp: {},
  flowDesign: {},
  formDesign: {
    selectedTheme: 'themeId',
    components: [
      {
        id: 'Input_1',
        version: '1.0',
        type: 'Input',
        title: '姓名',
        desc: '姓名',
        defaultValue: '',
        placeholder: '请输入姓名',
        colSpace: 4,
        unique: true,
        datasource: null,
      },
      {
        id: 'Input_2',
        version: '1.0',
        type: 'Input',
        title: '联系地址',
        desc: '联系地址',
        defaultValue: '',
        placeholder: '请输入联系地址',
        colSpace: 4,
        datasource: null,
      },
      {
        id: 'Select_1',
        version: '1.0',
        type: 'Select',
        title: '性别',
        desc: '性别',
        defaultValue: 'male',
        colSpace: 4,
        datasource: {
          type: 'custom',
          data: [
            {
              value: 'male',
              name: '男',
            },
            {
              value: 'female',
              name: '女',
            },
          ],
        },
      },
      {
        id: 'Select_2',
        version: '1.0',
        type: 'Select',
        title: '性别',
        desc: '性别',
        defaultValue: 'male',
        colSpace: 4,
        value: 'male',
        datasource: {
          type: 'app',
          appId: 'subapp1',
          fieldId: 'Input_1',
        },
      },
    ],
    layout: [['Input_1', 'Select_1'], ['Input_2'], ['Select_2']],
    events: {
      onchange: [
        {
          fieldId: 'Input_1',
          value: 'male',
          listeners: {
            visible: ['Input_2', 'Select_1'],
            reset: ['Input_2', 'Select_1'],
          },
        },
      ],
    },
    schema: {
      Input: {
        baseInfo: {
          name: '单行文本',
          icon: 'logo-icon',
          category: '基础组件',
          version: '1.0',
          type: 'Input',
        },
        config: [
          {
            key: 'title',
            defaultValue: '单行文本',
            label: '标题',
            type: 'Input',
            direction: 'vertical',
          },
          {
            key: 'desc',
            defaultValue: '单行文本',
            label: '标题',
            type: 'Input',
            direction: 'vertical',
          },
          {
            key: 'placeholder',
            defaultValue: '请输入',
            label: '占位文本',
            type: 'Input',
            direction: 'vertical',
          },
          {
            key: 'defaultValue',
            defaultValue: '',
            label: '默认值',
            type: 'Input',
            direction: 'vertical',
          },
          {
            key: 'maxLength',
            defaultValue: '无限制',
            label: '最大长度',
            type: 'Input',
            direction: 'vertical',
          },
          {
            key: 'colSpace',
            defaultValue: '4',
            label: '字段占比%',
            type: 'ColSpace',
            direction: 'vertical',
          },

          {
            key: 'required',
            defaultValue: false,
            label: '是否是必填项',
            type: 'Checkbox',
            direction: 'horizontal',
          },
          {
            key: 'disabled',
            defaultValue: false,
            label: '是否禁用',
            type: 'Checkbox',
            direction: 'horizontal',
          },
          {
            key: 'readonly',
            defaultValue: false,
            label: '是否只读',
            type: 'Checkbox',
            direction: 'horizontal',
          },
          {
            key: 'visible',
            defaultValue: true,
            label: '是否可见',
            type: 'Checkbox',
            direction: 'horizontal',
          },
          {
            key: 'allowClear',
            defaultValue: true,
            label: '是否允许清除',
            type: 'Checkbox',
            direction: 'horizontal',
          },
          {
            key: 'bordered',
            defaultValue: true,
            label: '是否带边框',
            type: 'Checkbox',
            direction: 'horizontal',
          },
        ],
      },
      Select: {
        baseInfo: {
          name: '下拉列表',
          icon: 'logo-icon',
          category: '基础组件',
          version: '1.0',
          type: 'Select',
        },
        config: [
          {
            key: 'title',
            defaultValue: '单行文本',
            label: '标题',
            type: 'Input',
            direction: 'vertical',
          },
          {
            key: 'desc',
            defaultValue: '单行文本',
            label: '标题',
            type: 'Input',
            direction: 'vertical',
          },
          {
            key: 'placeholder',
            defaultValue: '请输入',
            label: '占位文本',
            type: 'Input',
            direction: 'vertical',
          },
          {
            key: 'defaultValue',
            defaultValue: '',
            label: '默认值',
            type: 'Input',
            direction: 'vertical',
          },
          {
            key: 'maxLength',
            defaultValue: '无限制',
            label: '最大长度',
            type: 'Input',
            direction: 'vertical',
          },
          {
            key: 'colSpace',
            defaultValue: '4',
            label: '字段占比%',
            type: 'ColSpace',
            direction: 'vertical',
          },

          {
            key: 'required',
            defaultValue: false,
            label: '是否是必填项',
            type: 'Checkbox',
            direction: 'horizontal',
          },
          {
            key: 'disabled',
            defaultValue: false,
            label: '是否禁用',
            type: 'Checkbox',
            direction: 'horizontal',
          },
          {
            key: 'readonly',
            defaultValue: false,
            label: '是否只读',
            type: 'Checkbox',
            direction: 'horizontal',
          },
          {
            key: 'visible',
            defaultValue: true,
            label: '是否可见',
            type: 'Checkbox',
            direction: 'horizontal',
          },
          {
            key: 'allowClear',
            defaultValue: true,
            label: '是否允许清除',
            type: 'Checkbox',
            direction: 'horizontal',
          },
          {
            key: 'bordered',
            defaultValue: true,
            label: '是否带边框',
            type: 'Checkbox',
            direction: 'horizontal',
          },
        ],
      },
    },
    rules: [
      {
        type: 'reg',
        field: 'Input_1',
        validator: { type: 'constant', value: '(.+)$' },
      },
      {
        type: '<',
        field: 'Input_1',
        validator: { type: 'ref', value: 'Input_2' },
      },
      {
        type: '||',
        children: [
          {
            type: 'reg',
            field: 'Input_1',
            validator: /(.+)$/,
          },
          {
            type: '<',
            field: 'Input_1',
            validator: { type: 'ref', value: 'Input_2' },
          },
        ],
      },
    ],
    themes: [{}],
  },
};

export default componentSchema;
