const envs = {
  ALGOR_ORCH_BASE_SERVICE_ENDPOINT: window.ALGOR_ORCH_BASE_SERVICE_ENDPOINT,
  REACT_APP_LOGIN_DOMAIN: window.REACT_APP_LOGIN_DOMAIN,
  EASY_DOCK_BASE_SERVICE_ENDPOINT: window.EASY_DOCK_BASE_SERVICE_ENDPOINT,
  ALGOR_ORCH_FRONTEND_ENTRY: window.ALGOR_ORCH_FRONTEND_ENTRY,
};

// const envs = {
//   ALGOR_ORCH_BASE_SERVICE_ENDPOINT: process.env.REACT_APP_ORCH_DOMAIN!,
//   REACT_APP_LOGIN_DOMAIN: process.env.REACT_APP_LOGIN_DOMAIN!,
//   EASY_DOCK_BASE_SERVICE_ENDPOINT: process.env.REACT_APP_MAIN_DOMAIN!,
//   ALGOR_ORCH_FRONTEND_ENTRY: process.env.REACT_APP_ORCH_ENTRY!,
// };

export default envs;
